#!/bin/sh                                                                                       

PID="org.webosinternals.terminal"
PLG="termplugin"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the obsolete termplugin package
if [ -f $APPS/usr/lib/ipkg/info/org.webosinternals.termplugin.prerm ] ; then
  IPKG_OFFLINE_ROOT=$APPS sh $APPS/usr/lib/ipkg/info/org.webosinternals.termplugin.prerm || true
fi
/usr/bin/ipkg -o $APPS -force-depends remove org.webosinternals.termplugin || true

# Remove the terminal plugin
rm -f /usr/lib/BrowserPlugins/${PLG}.so

# Install the terminal plugin
install -m 755 $APPS/usr/palm/applications/${PID}/lib/${PLG}.so /usr/lib/BrowserPlugins/${PLG}.so

exit 0
