#!/bin/sh                                                                                       

PID="org.webosinternals.terminal"
PLG="termplugin"

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the terminal plugin
rm -f /usr/lib/BrowserPlugins/${PLG}.so

exit 0
